command: ["/bin/sh", "-c", ". /app/python/source_code/.venv/bin/activate && cd /app/python/source_code/backend && uvicorn main:app --host 0.0.0.0 --port 8000"]

env:
  - name: DATABRICKS_HOST
    value: "https://dbc-4ae1d974-bd72.cloud.databricks.com"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/594e3fa04e4efe25"
  - name: DATABRICKS_SERVING_ENDPOINT
    value: "databricks-gpt-oss-120b"
  - name: UC_ADMIN_GROUP
    value: "admin"
  - name: workspace_folder
    value: "/Workspace/NCSS/central"